### PR TITLE
Check if input word is valid

### PR DESCRIPTION
**Pull request by HyChriFo**
All commits compiled as one. Branches crudely merged. Sprint 1 complete. n+2 stories delivered.

- Words can be input with constraints on size of word
- Word Input needs to be valid
- Random word generated
- Input word correctness versus supplied word checked
- Words can be displayed
- Words displayed give users feedback on correctness of word
- Letters are displayed in blocks and are kept in row if guess is entered

### CODE REVIEW

**Review by TTRasemana — COMMENTED** [review]
The files organized  efficiently in relevant folders

**Review by TTRasemana — COMMENTED** [review]
Change ensures that the backspace does not occur when the row is empty

**Review by FalseCrystal — CHANGES_REQUESTED** [review]
GuessWords.test.js is in public, please move to private

**Review by TTRasemana — COMMENTED** [review]
Random Guess word integrated

**Review by FalseCrystal — COMMENTED** [review]
In CheckLetterInWord.js

The arrayLength, rightnessArray and variable, variables can be initialized using const instead of let as they are not edited after assignment.

Please name the variable variable to something appropriate like letterFlag

**Review by Keowa-1877616 — COMMENTED** [review]
Review of files Public/Script/colorChange.js and  Public/Script/inputLetters.js.

colorChange.js
- File contains short, precise code.
- Error checking has been implemented multiple times. (Good coding practice)
- Function is easy to implement and use.

inputLetters.js.
- File makes use of good naming conventions for function and variable names.
- Appropriate amount of comments added. This paired with the good naming conventions ensure easily understandable code.
- File does not export any functions. May need to add this for future use as the project develops.

**Review by TTRasemana — COMMENTED** [review]
boardscript.html moved to the script folder. This file completes all the functionality, is well structured and contains all the comments.

**Review by HyChriFo — COMMENTED** [review]
The words array is a convenient stop-gap for now but in the future, this is not ideal. Either a database needs to be created for this purpose and used or this code needs to perform querying to obtain a random word from an online database.

**Review by FalseCrystal — APPROVED** [review]

**Review by Cynthiack — APPROVED** [review]
boardScript.js Review:
Code structure and flow is readable and easily understood. Code formatting is adequate. Comments are included, giving sufficient explanations. Proper naming conventions are used and there are alignments making it easier to read the code. A defined architecture is followed and no hard coding is require. The code is maintainable, its modular. Functionalities are split into different functions. This code is easily tested. The issue serves its purpose, but may not be scalable, as it can only be run once for one player.

**Pull request merged**
